name: MHSFPV
version: '${project.version}'
main: me.devlongscript.mhsfpv.MHSFPV
api-version: '1.19'
authors: [dvelo]
description: Hiiii! my name is Plugin! whats yours?
website: https://mhsf.app

commands: 
  mhsf:
      usage: /<command>
      description: Link your account w/ MHSF